site_name: DorsetExplorer docs
plugins:
  - search
extra_css:
  - stylesheets/custom.css
theme:
  name: material
  logo: assets/dc_logo_white_d.svg
  favicon: assets/dc_logo_white_d.svg
  features:
    - navigation.instant
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to system preference

markdown_extensions:
- toc:
    permalink: true
- attr_list
- admonition
- pymdownx.details
- pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Dorset-Council-UK/GIFramework-Maps
copyright: All content is available under the Open Government Licence v3.0 except where otherwise stated. Screenshots contain OS data © Crown Copyright and database rights OS AC0000830671
nav:
    - 'index.md'
    - 'the-basics.md'
    - 'searching.md'
    - 'background-maps.md'
    - 'layers.md'
    - 'map-querying.md'
    - 'drawing.md'
    - 'measuring.md'
    - 'geolocation.md'
    - 'filtering.md'
    - 'sharing-your-map.md'
    - 'exporting-and-printing.md'
    - 'bookmarks.md'
    - 'copyright-and-acknowledgements.md'
    - 'terms-of-service.md'
    - 'privacy.md'
    - 'update-notes.md'
