site_name: DorsetExplorer docs
plugins:
  - search
extra_css:
  - stylesheets/custom.css
theme:
  name: material
  logo: assets/dc_logo_white_d.svg
  favicon: assets/dc_logo_white_d.svg
  features:
    - navigation.instant
  palette:
    primary: custom

markdown_extensions:
- toc:
    permalink: true
- attr_list
- admonition
- pymdownx.details
- pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Dorset-Council-UK/GIFramework-Maps
copyright: All content is available under the Open Government Licence v3.0 except where otherwise stated. Screenshots contain OS data © Crown Copyright and database rights OS AC0000830671
nav:
    - 'index.md'
    - 'the-basics.md'
    - 'searching.md'
    - 'background-maps.md'
    - 'layers.md'
    - 'map-querying.md'
    - 'drawing.md'
    - 'measuring.md'
    - 'geolocation.md'
    - 'filtering.md'
    - 'sharing-your-map.md'
    - 'exporting-and-printing.md'
    - 'bookmarks.md'
    - 'copyright-and-acknowledgements.md'
    - 'terms-of-service.md'
    - 'privacy.md'
    - 'update-notes.md'
